#Logging section settings
#levels are ordered as follows: TRACE < DEBUG < INFO < WARN < ERROR
logging:
  level:
    com:
      project:
        performance:
          PerformanceMonitorInterceptor: INFO
    org:
      springframework: INFO
    root: INFO